application: uirimalResources
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /(.+)
  static_files: static/\1
  upload: static/(.+)
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always